version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      RABBIT_HOST: 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
    hostname: 'rabbitmq'