version: '3'

services:
  web:
    build: .
    command: ["sh", "-c", "alembic upgrade head && python3 -m flask --app=main.py run --host=0.0.0.0 --port=5000"]
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      RABBIT_HOST: rabbitmq

    celery:
      build: .
      restart: always
      command: celery -A app.celery worker --loglevel=info --purge --pool-solo
      environment:
        RABBIT_HOST: rabbitmq

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
    hostname: 'rabbitmq'