version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: mongodb
      DB_HOST: db

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vacancy
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: vacancy

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vacancy
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_MONGODB_URL: mongodb://vacancy:mongopass@mongodb:27017/