version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"