"""empty message

Revision ID: 856c51f43c41
Revises: a06e0be41906
Create Date: 2023-02-25 22:38:55.900054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856c51f43c41'
down_revision = 'a06e0be41906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_creds', sa.Column('smtp_port', sa.Integer(), nullable=False))
    op.add_column('email_creds', sa.Column('pop_server', sa.String(length=120), nullable=True))
    op.add_column('email_creds', sa.Column('pop_port', sa.Integer(), nullable=True))
    op.add_column('email_creds', sa.Column('imap_server', sa.String(length=120), nullable=True))
    op.add_column('email_creds', sa.Column('imap_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_creds', 'imap_port')
    op.drop_column('email_creds', 'imap_server')
    op.drop_column('email_creds', 'pop_port')
    op.drop_column('email_creds', 'pop_server')
    op.drop_column('email_creds', 'smtp_port')
    # ### end Alembic commands ###
